import os.path

# do not edit this file directly for deployment specific config. instead,
# override individual settings in localsettings.py

PROXY_ROOT_DIR = os.path.dirname(__file__)

# do not override these; these are default fallbacks
DEFAULT_PORT = 8053
DEFAULT_SSL_CERT = os.path.join(PROXY_ROOT_DIR, 'ssl/debug.crt')
DEFAULT_USERS_DB = os.path.join(PROXY_ROOT_DIR, 'demo_users.csv')

# root url of the openclinica installation
OPENCLINICA_SERVER = 'https://75.144.154.137:8070/OpenClinica-ws/' # this is the staging server

# path to ssl certificate for https. if None, http-only
SSL_CERT = DEFAULT_SSL_CERT

# path to csv file containing user accounts for clinic users
USERS_DB = DEFAULT_USERS_DB

# path to the original screening xform (not currently needed)
SOURCE_XFORM = None

# 'location' field used in certain web service requests
CLINIC_NAME = 'TEST_CLINIC'

# minimum allowed length for clinic user PINs
MIN_PIN_LENGTH = 5

# path of bouncycastle jar file
BOUNCYCASTLE_JAR = '/usr/share/java/bcprov.jar'




try:
    from localsettings import *
except ImportError:
    pass
